---
title: "MainFile"
author: "Jackie Fountain"
date: "7/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries}
library(tidyverse)
```

```{r}
allchars <-read_tsv(here::here("data-raw","dnd_chars_all.tsv"))
```


```{r Single Levels Barchart}
allchars %>%
	subset(level<21) %>%
		#Building Bar Chart
	ggplot(aes(x=level))+
	geom_bar()+
	labs(title="Distribution of Adventurers by Level",
	x="Level",y="Frequency")

```

```{r Distribution of Adventurer Levels}
allchars %>%
    #Ready Data
  count(levelGroup) %>%
  mutate(levelG=fct_relevel(levelGroup,"1-3","4-7","8-11","12-15",
  	"16-18","19-20"))%>%
	#Build Bar Chart
  ggplot(aes(x=levelG,y=n,color=levelG))+geom_bar(stat="identity")+
    geom_text(aes(label=n), vjust=-.3, color="black", size=3.5)+
    theme(legend.position="none")+
	labs(title="Distribution of Adventurers by Level Range",
	x="Level Range",y="Count")
```

```{r Average of Stats of Starting Characters}
#Add distributions as well
allchars %>%
	subset(level<2)%>%
	#Manipulate Data: Calculating Means
 summarise(STR=mean(Str),DEX=mean(Dex),
		   CON=mean(Con),INT=mean(Int),
		   WIS=mean(Wis),CHA=mean(Cha)) %>%
	#Pivot Table and Ordering Abilities
 pivot_longer(
    cols = `STR`:`CHA`,
    names_to = "Stat",
    values_to = "AverageValue")%>%
	mutate(Ability=fct_relevel(Stat,"STR","DEX","CON","INT","WIS","CHA"))%>%
	#Building Bar Chart
	ggplot(aes(x=Ability,y=AverageValue,color=Ability))+
	geom_bar(stat="identity")+ 
    geom_text(aes(label=round(AverageValue,digits=2)), 
      vjust=1.6, color="white", size=3.5)+
      theme(legend.position="none")+
	  labs(title="Average of Each Ability Score", 
	  x="Ability Score",y="Average Value")
```
```{r Five Number Summaries of Stats}
numSums <-allchars %>%
	subset(level<2)%>%
	summarise(Variable=c("Min","Q1","Median","Mean","Q3","Max")
			  ,STR=summary(Str),DEX=summary(Dex),
		   CON=summary(Con),INT=summary(Int),
		   WIS=summary(Wis),CHA=summary(Cha))
```

```{r random level 1 character stats}
set.seed(12345)                          # Set seed for reproducibility

allchars %>%
	subset(level<2, processedRace != "NA")%>%
	sample_n(10)%>%
	select(processedRace, class, Str:Cha)
```





```{r Races}
#Two barcharts one with races and one with subraces included
allchars %>%
	count(race)%>%
    arrange(desc(n)) %>%
    slice(1:10) %>% #looking at top 10
#Building Bar Chart
	ggplot(aes(x=race,y=n,color=race))+ geom_bar(stat="identity")

allchars %>%
	count(processedRace)%>%
arrange(desc(n)) %>%
    slice(1:10) %>%
#Building Bar Chart
	ggplot(aes(x=processedRace,y=n,color=processedRace))+ geom_bar(stat="identity")

	
```













